json.id company.id
json.name company.name
json.website company.website
json.category company.category.name
json.city company.city.name
json.address company.address
json.about company.about
json.created_at company.created_at
json.updated_at company.updated_at
